services:
  caddy-proxy:
    image: phillarmonic/domainpilot:2
#    build:
#      context: .
#      dockerfile: docker/Dockerfile
    cap_add:
      - NET_ADMIN
    environment:
      - DEBUG=0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./caddy_data:/data
      - ./caddy_config:/config
      - ./host-routes.conf:/opt/host-routes.conf
    ports:
      - "${CADDY_HTTP_PORT:-80}:80"
      - "${CADDY_HTTPS_PORT:-443}:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
        - domainpilot-proxy
    restart: unless-stopped

networks:
  domainpilot-proxy:
        external: true