services:
  caddy-proxy:
    image: phillarmonic/domainpilot:2
#    build:
#      context: .
#      dockerfile: docker/Dockerfile
    cap_add:
      - NET_ADMIN
    environment:
      - DEBUG=0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./caddy_data:/data
      - ./caddy_config:/config
      - ./host-routes.conf:/opt/host-routes.conf
    ports:
      - "${CADDY_HTTP_PORT:-80}:80"
      - "${CADDY_HTTPS_PORT:-443}:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
        - domainpilot-proxy
    restart: unless-stopped
    healthcheck:
          test: ["CMD", "curl", "-fks", "https://localhost/_healthz"]
          interval: 30s
          timeout: 10s
          retries: 3
          start_period: 20s # Give Caddy time to initialize and generate certs
    tty: true
    stdin_open: true

networks:
  domainpilot-proxy:
        external: true