name: "Build and push Docker Image"

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      caddy_version:
        description: "Choose a Caddy Version"
        default: "2"
        required: true

jobs:
  build_domainpilot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract version information
        id: version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            # Remove 'v' prefix if it exists
            VERSION=${VERSION#v}
            MAJOR_VERSION=$(echo $VERSION | cut -d. -f1)
          else
            VERSION=${{ github.event.inputs.caddy_version }}
            MAJOR_VERSION=${{ github.event.inputs.caddy_version }}
          fi
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "major_version=${MAJOR_VERSION}" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build and push - Alpine
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            CADDY_VERSION=${{ github.event.inputs.caddy_version || 2 }}
          tags: |
            phillarmonic/domainpilot:latest
            phillarmonic/domainpilot:${{ steps.version.outputs.major_version }}
            phillarmonic/domainpilot:${{ steps.version.outputs.version }}