name: "Build and push Docker Image"

on:
  workflow_dispatch:
    inputs:
      caddy_version:
        description: "Choose a Caddy Version"
        default: "2"
        required: true
jobs:
  build_domainpilot:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build and push - Alpine
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            CADDDY_VERSION=${{ github.event.inputs.caddy_version }}
          tags: |
            phillarmonic/domainpilot:${{ github.event.inputs.caddy_version }}